import 'package:flutter/material.dart';
import 'package:my_project/data/models/wallet.dart';
import 'package:my_project/data/models/wallet_category.dart';
import 'package:my_project/domain/repository/wallet.dart';
import 'package:my_project/domain/repository/wallet_category.dart';
import 'package:my_project/service_locator.dart';

class WalletAddScreen extends StatefulWidget {
   // Replace with actual user ID
  const WalletAddScreen({super.key});

  @override
  _WalletAddScreenState createState() => _WalletAddScreenState();
}

class _WalletAddScreenState extends State<WalletAddScreen> {
  final _formKey = GlobalKey<FormState>();

  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _balanceController = TextEditingController();
  final TextEditingController _currencyController = TextEditingController();

  WalletCategory? _selectedCategory;
  List<WalletCategory> categories = [];

  bool isLoading = false;
  String? error;

  @override
  void initState() {
    super.initState();
    _loadCategories();
  }

  Future<void> _loadCategories() async {
    final userId = 'userId'; // Replace with actual user ID
    setState(() => isLoading = true);
    try {
      // Load categories from the repository
      // Assuming you have a method to get categories
      final result = await sl<WalletCategoryRepository>().getWalletCategoryByOnlyUserId(userId);
      result.fold(
        (errorMessage) => setState(() => error = errorMessage),
        (data) => setState(() => categories = data),
      );
    } catch (e) {
      setState(() => error = "Error: $e");
    } finally {
      setState(() => isLoading = false);
    }
  }

  void _showSnackbar(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message, style: TextStyle(color: Colors.white)),
        backgroundColor: Colors.black,
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  Future<void> _createWallet() async {
    if (!_formKey.currentState!.validate() || _selectedCategory == null) {
      _showSnackbar("Please fill all fields and select a category");
      return;
    }

    try {
      final wallet = Wallet(
        id: '', // Assuming ID is generated by the backend
        balance: double.tryParse(_balanceController.text) ?? 0,
        currency: _currencyController.text,
        createdTime: DateTime.now(),
        lastUpdatedTime: DateTime.now(),
        userId: 'userId', // Replace with actual user ID
        walletCategory: _selectedCategory!,
      );

      final result = await sl<WalletRepository>().createWallet(wallet);
      result.fold(
        (errorMessage) => _showSnackbar(errorMessage),
        (data) {
          _showSnackbar("Wallet created successfully!");
          Navigator.pop(context, data);
        },
      );
    } catch (e) {
      _showSnackbar("Error: $e");
    }
  }

  InputDecoration _inputDecoration(String label) {
    return InputDecoration(
      labelText: label,
      filled: true,
      fillColor: Colors.grey[200],
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide.none,
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: BorderSide(color: Colors.green, width: 2),
      ),
      contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 14),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Add Wallet"),
        centerTitle: true,
        backgroundColor: Colors.green,
        elevation: 0,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: isLoading
            ? Center(child: CircularProgressIndicator())
            : Form(
                key: _formKey,
                child: Column(
                  children: [
                    TextFormField(
                      controller: _nameController,
                      decoration: _inputDecoration("Name"),
                      validator: (value) =>
                          value?.isEmpty ?? true ? "Required field" : null,
                    ),
                    SizedBox(height: 12),
                    TextFormField(
                      controller: _descriptionController,
                      decoration: _inputDecoration("Description"),
                      validator: (value) =>
                          value?.isEmpty ?? true ? "Required field" : null,
                    ),
                    SizedBox(height: 12),
                    TextFormField(
                      controller: _balanceController,
                      decoration: _inputDecoration("Balance"),
                      keyboardType: TextInputType.number,
                      validator: (value) =>
                          value?.isEmpty ?? true ? "Required field" : null,
                    ),
                    SizedBox(height: 12),
                    TextFormField(
                      controller: _currencyController,
                      decoration: _inputDecoration("Currency"),
                      validator: (value) =>
                          value?.isEmpty ?? true ? "Required field" : null,
                    ),
                    SizedBox(height: 12),
                    DropdownButtonFormField<WalletCategory>(
                      value: _selectedCategory,
                      decoration: _inputDecoration("Category"),
                      isExpanded: true,
                      items: categories.map((category) {
                        return DropdownMenuItem<WalletCategory>(
                          value: category,
                          child: Text(category.name),
                        );
                      }).toList(),
                      onChanged: (value) {
                        setState(() {
                          _selectedCategory = value;
                        });
                      },
                      validator: (value) =>
                          value == null ? "Required field" : null,
                    ),
                    SizedBox(height: 20),
                    ElevatedButton(
                      onPressed: _createWallet,
                      child: Text("Create"),
                    ),
                  ],
                ),
              ),
      ),
    );
  }
}